services:
  # Django Application
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - townmarket

  # Celery Worker
  celery_worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - townmarket

  # Celery Beat (Scheduler)
  celery_beat:
    build: .
    command: celery -A core beat --loglevel=info --schedule /tmp/celerybeat-schedule
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - townmarket

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6389:6379"
    volumes:
      - redis_data:/data
    networks:
      - townmarket

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    networks:
      - townmarket

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  townmarket:
    driver: bridge
