# Generated by Django 6.0.3 on 2026-03-12 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_parentproductcategory_productcategory_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='sub_category',
        ),
    ]
