# Generated by Django 6.0.3 on 2026-03-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_parentproductcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategoryoptionvalue',
            name='value',
            field=models.TextField(),
        ),
    ]
