# Generated by Django 6.0.3 on 2026-03-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productcategoryoptionvalue_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategoryoption',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
