# Generated by Django 6.0.3 on 2026-04-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='reserved_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
