# Generated by Django 6.0.3 on 2026-04-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategoryoptionvalue',
            options={'ordering': ['created_at']},
        ),
    ]
