# Generated by Django 6.0.3 on 2026-04-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productcategoryoptionvalue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategoryoptionvalue',
            options={'ordering': ['-created_at']},
        ),
    ]
