# Generated by Django 6.0.3 on 2026-04-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_productcategoryoptionvalue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategoryoptionvalue',
            options={},
        ),
    ]
