# Generated by Django 6.0.3 on 2026-08-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_non_negative'),
        ),
    ]
