# Generated by Django 6.0.3 on 2026-08-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_stock_non_negative_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='reserved_quantity_non_negative'),
        ),
    ]
