# Generated by Django 6.0.3 on 2026-08-26 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_productvariant_reserved_quantity_non_negative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategoryoption',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_options', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategoryoptionvalue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_option_values', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductCategoryOptionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('option_name', models.CharField(max_length=200)),
                ('value_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_audits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
