# Generated by Django 6.0.3 on 2026-08-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_productcategoryoption_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
