# Generated by Django 6.0.3 on 2026-03-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_request_for_shop',
            field=models.BooleanField(default=False),
        ),
    ]
