# Generated by Django 6.0.3 on 2026-03-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_request_for_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_request_for_shop',
            field=models.CharField(choices=[('request_pending', 'request_pending'), ('request_approved', 'request_approved'), ('request_not_requested', 'request_not_requested')], default='request_not_requested', max_length=25),
        ),
    ]
