# Generated by Django 6.0.3 on 2026-08-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otp',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
