# Generated by Django 6.0.3 on 2026-08-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_otp_bruteforce_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
