"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
from datetime import timedelta
from decimal import Decimal

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ✅ Security Settings
# ✅ Never hardcode secrets - use environment variables
# ✅ Production-ready defaults

# ✅ SECRET_KEY
SECRET_KEY = config('SECRET_KEY')

# ✅ DEBUG
DEBUG = config('DEBUG', default=False, cast=bool)

# ✅ ALLOWED_HOSTS - Production ready, never ['*']
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,townmarket-web-dev,townmarket_web_dev,web',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

# ✅ Trust proxy headers (ngrok/reverse proxy) so absolute URLs use HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# ✅ CSRF Trusted Origins - configured for development/ngrok
CSRF_TRUSTED_ORIGINS = [
    'https://overrigged-botanically-lila.ngrok-free.dev',
    "http://172.24.0.1:3000",
    "http://localhost:3000",
    "https://unluckier-dorie-nontumultuous.ngrok-free.dev",
    'https://outmatch-marvelous-mummify.ngrok-free.dev'
]

# ✅ CORS Settings - Production safe
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=False, cast=bool)
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()]
)
CORS_ALLOW_CREDENTIALS = True


# ✅ Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'phonenumber_field',
    'channels',
    'shop',
    'django_filters',
    'product',
    'cart',
    'order',
    'invoice',
    'review',
    'chat',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'accounts.CustomUser'

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [config('REDIS_URL', default='redis://redis:6379/1')],
        },
    },
}

# ✅ Celery settings
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://redis:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://redis:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# ✅ Core business settings
SHIPPING_FEE = config('SHIPPING_FEE', default=50, cast=int)
ORDER_PAYMENT_TIMEOUT_MINUTES = config('ORDER_PAYMENT_TIMEOUT_MINUTES', default=5, cast=int)
# Merchant settings
STORE_ID = config('STORE_ID')
STORE_PASSWORD = config('STORE_PASSWORD')

# ✅ SSLCommerz URLs configurable — never hardcode sandbox in production.
SSLCOMMERZ_API_URL = config(
    'SSLCOMMERZ_API_URL',
    default='https://sandbox.sslcommerz.com/gwprocess/v4/api.php',
)
SSLCOMMERZ_VALIDATION_URL = config(
    'SSLCOMMERZ_VALIDATION_URL',
    default='https://sandbox.sslcommerz.com/validator/api/validationserverAPI.php',
)

# ✅ SMS Configuration
SMS_API_KEY = config('SMS_API_KEY', default='')

# ✅ bKash Payment Gateway (PGW) settings
BKASH_APP_KEY = config('BKASH_APP_KEY', default='')
BKASH_APP_SECRET = config('BKASH_APP_SECRET', default='')
BKASH_BASE_URL = config(
    'BKASH_BASE_URL',
    default='https://sandbox.pay.bka.sh/v1.2.0-beta',
)

# ✅ Celery Beat settings for periodic tasks
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'cancel-expired-pending-orders': {
        'task': 'order.tasks.cancel_expired_pending_orders',
        'schedule': crontab(minute='*/15'),  # Run every 15 minutes
    },
    'cleanup-unverified-users': {
        'task': 'accounts.task.cleanup_unverified_users',
        'schedule': crontab(minute='*/10'),  # Run every 10 minutes
    },
    'release-expired-cart-stock': {
        'task': 'cart.tasks.release_expired_cart_stock',
        'schedule': crontab(minute='*/10'),  # Run every 10 minutes
    },
}
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Dhaka'

# ✅ Commission percentage
COMMISSION_PERCENTAGE = config('commission_percentage', default=0.10, cast=Decimal)

# ✅ JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ✅ REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    # Global throttling to mitigate brute-force / credential-stuffing.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/minute',
        'user': '120/minute',
    },
}

# ✅ Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default='sqlite:///db.sqlite3'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# ✅ Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ✅ Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ✅ Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATIC_ROOT = BASE_DIR / "staticfiles"


# ✅ Cloudflare Services - import configuration module
# All Cloudflare service settings are centralized in core.cloudflare
# This allows easy management and switching between services
try:
    from core.cloudflare import r2, is_r2_configured, get_service_status, R2
except ImportError:
    # Fallback if cloudflare module not available (e.g., minimal deployment)
    r2 = None
    is_r2_configured = lambda: False
    get_service_status = lambda: {}
    R2 = None

# ✅ R2 Configuration - derived from cloudflare module
# These are exposed for Django storage backends and template usage
CLOUDFLARE_R2_ACCOUNT_ID = os.getenv('CLOUDFLARE_R2_ACCOUNT_ID', '104dbc5609bc33780236c732ecf740dd')
CLOUDFLARE_R2_ACCESS_KEY_ID = os.getenv('CLOUDFLARE_R2_ACCESS_KEY_ID', '')
CLOUDFLARE_R2_SECRET_ACCESS_KEY = os.getenv('CLOUDFLARE_R2_SECRET_ACCESS_KEY', '')
CLOUDFLARE_R2_BUCKET_NAME = os.getenv('CLOUDFLARE_R2_BUCKET_NAME', 'townmarket')

# ✅ Storage backends - use R2 for both media and static files
# These strings are required by Django's settings system
DEFAULT_FILE_STORAGE = 'storages.backends.cloudflare.CloudFileStorage'
STATICFILES_STORAGE = 'storages.backends.cloudflare.StaticCloudFileStorage'

# ✅ R2 endpoint is auto-derived from account ID:
# Format: https://<account-id>.r2.cloudflarestorage.com
# No manual endpoint configuration needed
# The actual R2 instance is available via: from core.cloudflare import r2

# ✅ Optional: Custom domain (e.g., files.yourdomain.com)
# Set CLOUDFLARE_R2_CUSTOM_DOMAIN env var to use custom CNAME
CLOUDFLARE_R2_CUSTOM_DOMAIN = os.getenv('CLOUDFLARE_R2_CUSTOM_DOMAIN', default='')

# ✅ File management settings
AWS_S3_FILE_OVERWRITE = False  # Prevent overwriting existing files on re-upload
DEFAULT_FILE_ACL = 'public-read'  # Allow public access to uploaded files
FILE_POST_DELETE = True  # Delete files from R2 when Django model deleted

# ✅ Cache control for uploaded files
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
    'ServerSideEncryption': 'AES256',
}


# ✅ OAuth / Social Auth settings (placeholder for future)
# GOOGLE_OAUTH2_CLIENT_ID = config('GOOGLE_OAUTH2_CLIENT_ID', default='')
# GOOGLE_OAUTH2_CLIENT_SECRET = config('GOOGLE_OAUTH2_CLIENT_SECRET', default='')