# Generated by Django 6.0.3 on 2026-03-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_market_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
