# Generated by Django 6.0.3 on 2026-03-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_deactivated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='deactivated',
            new_name='is_deactivated',
        ),
    ]
