# Generated by Django 6.0.3 on 2026-03-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_requestforshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/market_cover_images/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/shop_cover_images/'),
        ),
    ]
