# Generated by Django 6.0.3 on 2026-03-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_market_cover_image_alter_shop_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='market_cover_images/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_cover_images/'),
        ),
    ]
