# Generated by Django 6.0.3 on 2026-04-16 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_shoporder_comission_given'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=500, unique=True)),
                ('val_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('store_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('gateway_status', models.CharField(blank=True, max_length=50, null=True)),
                ('card_type', models.CharField(max_length=100)),
                ('card_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('card_issuer', models.CharField(blank=True, max_length=255, null=True)),
                ('card_issuer_country', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(default='sslcommerze', max_length=100)),
                ('risk_level', models.CharField(blank=True, max_length=50, null=True)),
                ('risk_title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_ipn_verified', models.BooleanField(default=False)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'VALID')), fields=('order',), name='unique_valid_invoice_per_order')],
            },
        ),
    ]
