# Generated by Django 6.0.3 on 2026-04-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='comission_given',
            field=models.BooleanField(default=False),
        ),
    ]
