# Generated by Django 6.0.3 on 2026-04-16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_shoporder_comission_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_upazilla',
            field=models.CharField(blank=True, choices=[('feni_sadar', 'Feni Sadar'), ('parshuram', 'Parshuram'), ('chagalaiya', 'Chagalaiya'), ('daganbhuiyan', 'Daganbhuiyan'), ('sonagazi', 'Sonagazi'), ('fulgazi', 'Fulgazi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Please provide a valid Bangladeshi mobile number.', regex='^(?:\\+88|88)?(01[3-9]\\d{8})$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, choices=[('feni', 'Feni'), ('dhaka', 'Dhaka'), ('chattogram', 'Chattogram')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(blank=True, default='Bangladesh', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, default='3900', max_length=20),
        ),
    ]
