# Generated by Django 6.0.3 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_validation_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, choices=[('feni', 'Feni')], max_length=100),
        ),
    ]
