# Generated by Django 6.0.3 on 2026-04-23 10:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_confirmed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyDectedButOrderFailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('transction_id', models.CharField(blank=True, max_length=1000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('card_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_deducted_but_failed', to='order.order')),
            ],
        ),
    ]
