# Generated by Django 6.0.3 on 2026-08-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_moneydectedbutorderfailed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneydectedbutorderfailed',
            old_name='transction_id',
            new_name='transaction_id',
        ),
    ]
