# Generated by Django 6.0.3 on 2026-08-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_transction_to_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('sslcommerz', 'SSLCommerz Payment'), ('bkash', 'bKash Payment')], default='sslcommerz', max_length=50),
        ),
    ]
