# Generated by Django 6.0.3 on 2026-08-31 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_cod_amount_order_shipping_fee_and_more'),
        ('shop', '0009_alter_market_cover_image_alter_shop_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialledgerentry',
            name='category',
            field=models.CharField(choices=[('customer_payment', 'Customer Payment'), ('platform_commission', 'Platform Commission'), ('merchant_product_earning', 'Merchant Product Earning'), ('shipping_collected', 'Shipping Collected'), ('customer_refund', 'Customer Refund'), ('merchant_settlement', 'Merchant Settlement'), ('commission_payment', 'Commission Payment'), ('cancellation_charge', 'Cancellation Charge'), ('cod_collected', 'COD Collected')], max_length=30),
        ),
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('liability_before', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('liability_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_method', models.CharField(default='manual', max_length=50)),
                ('transaction_reference', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('failed', 'Failed')], db_index=True, default='received', max_length=20)),
                ('overpay_credit', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_commission_payments', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payments', to='shop.shop')),
                ('shop_orders', models.ManyToManyField(related_name='commission_payments', to='order.shoporder')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'transaction_reference'), name='unique_commission_payment_ref_per_shop')],
            },
        ),
    ]
