# Generated by Django 6.0.3 on 2026-08-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_financialledgerentry_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionpayment',
            name='overpaid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='commission_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission amount already paid against this shop order (FIFO allocation).', max_digits=12),
        ),
    ]
