# Generated by Django 6.0.3 on 2026-08-31 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_commissionpayment_overpaid_amount_and_more'),
        ('shop', '0009_alter_market_cover_image_alter_shop_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPaymentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order.commissionpayment')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payment_lines', to='shop.shop')),
                ('shop_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payment_lines', to='order.shoporder')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'constraints': [models.UniqueConstraint(fields=('payment', 'shop_order'), name='unique_commission_payment_line_per_order')],
            },
        ),
    ]
